# 端口
server:
  port: 9003

# sa-token配置
sa-token:

  # SSO-相关配置
  sso:
    # SSO-Server端-单点登录授权地址 模式二
    auth-url: http://sa-sso-server.com:9000/sso/auth
    # SSO-Server端-单点注销 模式二
    is-slo: true
    # 单点注销地址
    slo-url: http://sa-sso-server.com:9000/sso/logout
    # 打开模式三（使用Http请求校验ticket）
    is-http: true
    # SSO-Server端 ticket校验地址
    check-ticket-url: http://sa-sso-server.com:9000/sso/checkTicket
    # SSO-Server端 查询userinfo地址
    userinfo-url: http://sa-sso-server.com:9000/sso/userInfo
    # 接口调用秘钥（用于SSO模式三的单点注销功能）
    secretkey: kQwIOrYvnXmSDkwEiFngrKidMcdrgKor

  # 配置Sa-Token单独使用的Redis连接 （此处需要和SSO-Server端连接同一个Redis）
  alone-redis:
    # Redis数据库索引
    database: 2
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接超时时间
    timeout: 10s