# 端口
server:
  port: 9002

# sa-token配置
sa-token:
  # SSO-相关配置
  sso:
    # SSO-Server端-单点登录授权地址 模式二
    auth-url: http://sa-sso-server.com:9000/sso/auth
    # SSO-Server端-单点注销 模式二
    is-slo: true

  # 配置Sa-Token单独使用的Redis连接 （此处需要和SSO-Server端连接同一个Redis）
  alone-redis:
    # Redis数据库索引
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接超时时间
    timeout: 10s