server:
  port: 3344
spring:
  application:
    name: config-center-service
  cloud:
    config:
      server:
        git:
          #uri: git@github.com:morikawaaoi/work.git
          uri: git@github.com:morikawaaoi/work.git
          search-paths:
            - work
      label: master
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka