server:
  port: 8092


spring:
  application:
    name: consumer-feign-order-service


eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
ribbon:
  #建立链接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间   feign默认超时时间1s
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000
logging:
  level:
    #feign日志以什么级别监控哪个端口
    learn.springcloud.service.PaymentFeignService: debug
