server:
  port: 9527
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes: #当访问localhost:8001时 会自动转发到locahost:9527 (再断言成立的情况下)
        - id: payment_routh #路由的ID，没有固定的规则但是要求唯一，建议配合服务名
         # uri: http://localhost:8001  #匹配后提供服务的路由地址
          uri: lb:http://PROVIDER-PAYMENT-SERVICE #匹配后提供服务的路由地址;/''
          predicates:
            - Path=/payment/get/**  #断言，路径相匹配的进行路由

        - id: payment_routh2 #路由的ID，没有固定的规则但是要求唯一，建议配合服务名
          # uri: http://localhost:8001  #匹配后提供服务的路由地址
          uri: lb:http://PROVIDER-PAYMENT-SERVICE #匹配后提供服务的路由地址
          #filter: - AddRequestParameter=X-Request-Id,1024 #过滤器工厂会在匹配的请求头加上一堆请求头，名称为X-Request-Id的值为1024
          predicates:
            - Path=/payment/lb/**  #断言，路径相匹配的进行路由
            - After=2022-05-02T16:06:26.732+08:00[Asia/Shanghai]
            # - Query=username, \d+ #要有参数名username 并且值还得是整数才能路由
            # - Method=GET #要是get方法
            # - Host=**.sp.com #host地址
           # - Cookie=username,73588
           # - Header=X-Request-Id, \d+ #请求头要带有X-Request-Id属性并且值为整数

eureka:
  instance:
    hostname: gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
