server:
  port: 8092
spring:
  application:
    name: consumerconsul-order-service

  cloud:
    consul:
      discovery:
        host: localhost
        port: 8500
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true
