server:
  port: 8090

jap:
  basic:
    sso: false
    cache-expire-time: 12
    token-expire-time: 12

  sso:
    cookie-domain: xx
    cookie-max-age: 30
    cookie-name: xxx

  simple:
    username-field: username
    password-field: password
    remember-me-field: rememberMe
    remember-me-cookie-key: rememberMeCookieKey