server:
  port: 8001
spring:
  application:
    name: provider-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #使用druid数据源，替换C3P0
    url: jdbc:mysql://localhost:3306/shop?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: mysql123456
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: learn.springcloud.entity
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment01
    prefer-ip-address: true